#include "rainbow_palette.h"

#define _USE_MATH_DEFINES
#include <cstdio>
#include <cmath>

RainbowPalette::RainbowPalette(int size, int depth): Palette(size, depth) {
    int idx = 0;
    for (int i = 0; i < size; i++) {
        idx = i * depth;

        // The rainbow is generated by three sine waves offset 120 degrees from each other
        data_[idx] = calculateChannelValue(i, size, 0); // red
        data_[idx+1] = calculateChannelValue(i, size, 2 * M_PI / 3); // green
        data_[idx+2] = calculateChannelValue(i, size, 4 * M_PI / 3); // blue

        printf("%02x %02x %02x\n", data_[idx], data_[idx+1], data_[idx+2]);
    }
}

int RainbowPalette::calculateChannelValue(int step, int size, float channelPhase) {
    const float amplitude = 255 / 2; // Chosen to ensure a range of 0-255 for the function's output
    const float offset = 255 / 2; // Chosen to ensure a range of 0-255 for the function's output
    float phase = channelPhase + M_PI; // Offset by an extra 180 degrees to get a purple-ish base color
    float freq = 2 * M_PI / size;

    return sin(freq * step + phase) * amplitude + offset;
}